# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

- Jason Yang
- Xiao Du
-

## Research Question

What is the difference-in-differences estimate of the post-2017 change in unemployment rates between high AI exposure majors (Computer Science, Engineering, Mathematics, and Physics) and low AI exposure majors (History, Art, Philosophy, and Political Science) for Bachelor's degree in the US?

(**We use 2017 as the cutoff year because it marks the rise of modern Transformer-based AI, allowing us to compare unemployment trends before and after this technological shift.)

The specification of AI exposure level is based on the result of AI's direct and potential impact on different subject fields from Gao and Wang's 2023 research. (https://www.semanticscholar.org/paper/Quantifying-the-Benefit-of-Artificial-Intelligence-Gao-Wang/e2f04c45223ab68cfd0ec7a2f11a27347e3565e0)

**Refer to the following graph:**
![description](WechatIMG358.jpg)

## Background and Prior Work

As many college students approach graduation, concerns about employment prospects and decisions regarding graduate education have become increasingly significant. The rapid development of artificial intelligence (AI), particularly following the introduction of the Transformer architecture in 2017, has substantially reshaped both scientific research and labor market demands. Previous research has documented the uneven adoption of AI across different academic fields. Hajkowicz et al. (2023) conducted a bibliometric analysis covering 333 research fields from 1960 to 2021 and found that AI adoption varies significantly across the physical sciences, natural sciences, life sciences, social sciences, and the arts and humanities. Thayyib et al. (2023) found that key AI technologies such as machine learning, deep learning, and natural language processing remain concentrated in specific domain clusters, while other fields such as engineering and biomedical sciences show relatively limited AI application. Additionally, Gao and Wang (2023) developed a framework to quantify both the direct use and potential benefits of AI across scientific disciplines, suggesting that AI may exacerbate existing inequalities across fields. While these studies provide valuable insights into the differential impact of AI across disciplines, relatively little research has examined how majors with different levels of AI exposure have experienced changes in employment outcomes and graduate school enrollment trends. This study aims to address this gap by analyzing post-2017 trends among UC San Diego students using data on employment outcomes, industries, graduation years, and graduate school enrollment across different majors. The goal is to investigate whether AI exposure has become a significant factor shaping undergraduate career and educational trajectories.

References
Hajkowicz et al. (2023). https://www.semanticscholar.com/paper/Artificial-intelligence-adoption-in-the-physical-A-Hajkowicz-Sanderson/4d0d70769451c0f4e702bf860da26d58fa33e81b
Thayyib et al. (2023). https://www.semanticscholar.com/paper/State-of-the-Art-of-Artificial-Intelligence-and-Big-Thayyib-Mamilla/641b46fc44d6c7db82640ad6f15da260589513ef
Gao & Wang (2023). https://www.semanticscholar.com/paper/Quantifying-the-Benefit-of-Artificial-Intelligence-Gao-Wang/e2f04c45223ab68cfd0ec7a2f11a27347e3565e0

## Hypothesis

**Null Hypothesis:**
There is no difference-in-differences effect in unemployment rates between high-AI-exposure majors (Computer Science, Engineering, Mathematics, and Physics) and low-AI-exposure majors (History, Art, Philosophy, and Political Science) after 2017.

**Alternative Hypothesis:**
There is a significant difference-in-differences effect in unemployment rates between high-AI-exposure majors and low-AI-exposure majors after 2017.

We hypothesize that there is a significant difference-in-differences effect in unemployment rates between high-AI-exposure majors and low-AI-exposure majors after 2017 (the rise of Transformer). We think so because majors with higher exposure to AI are more likely to play significant roles in the rapid expansion of AI in various industries, therefore vastly impacting students’ future employment and unemployement.

## Data

### Dataset #1

Dataset Name:
NCES Digest of Education Statistics Table 505.10: Employment outcome of 25- to 29-year-old bachelor’s degree holders by field of study, 2012–2021.

Link to the dataset:

https://nces.ed.gov/programs/digest/d22/tables/dt22_505.10.asp
https://nces.ed.gov/programs/digest/d21/tables/dt21_505.10.asp
https://nces.ed.gov/programs/digest/d20/tables/dt20_505.10.asp
https://nces.ed.gov/programs/digest/d19/tables/dt19_505.10.asp
https://nces.ed.gov/programs/digest/d18/tables/dt18_505.10.asp
https://nces.ed.gov/programs/digest/d17/tables/dt17_505.10.asp
https://nces.ed.gov/programs/digest/d16/tables/dt16_505.10.asp
https://nces.ed.gov/programs/digest/d15/tables/dt15_505.10.asp
https://nces.ed.gov/programs/digest/d14/tables/dt14_505.10.asp
https://nces.ed.gov/programs/digest/d13/tables/dt13_505.10.asp

Number of observations:
The raw data come from 10 NCES tables, covering 2012–2021. Each table contains multiple field-of-study rows. For our cleaned dataset, we will extract 8 selected majors across 10 years, giving 80 major-year observations.

Number of variables:
Each raw NCES table has 12 main columns, including field of study, number of degree holders, unemployment rate, median earnings, and related percentage measures. For our cleaned dataset, we will use or create 6 main variables: major, year, unemployment_rate, ai_exposure_group, post_2017, and did_interaction.

Description of the variables most relevant to this project:
The main dependent variable is unemployment_rate, which reports unemployment rates for 25- to 29-year-old bachelor’s degree holders by field of study. The major variable identifies the field of study. We classify Computer Science, Engineering, Mathematics, and Physics as high-AI-exposure majors, and History, Art, Philosophy, and Political Science as low-AI-exposure majors. We also create post_2017 to separate years before and after 2017, and did_interaction as the key variable for the difference-in-differences model (It equals 1 only when both conditions are true: 1) The major is in the high-AI-exposure group. 2) The year is after 2017).

Description of any shortcomings this dataset has with respect to the project:
The raw NCES tables are not already in panel format, so we need to manually extract and clean the relevant major-year observations. Some NCES field names also do not perfectly match our simplified major names. For example, Computer Science appears as Computer and information sciences, and Physics may be included under Physical sciences. The dataset is observational, so the results cannot fully prove causation. The analysis is also limited by the small number of majors and by possible outside shocks, such as COVID-19 and broader labor-market changes.

How this dataset will be used:
We will convert the NCES tables into a cleaned panel dataset where each row represents one major in one year. Then we will use a difference-in-differences model to compare changes in unemployment rates after 2017 between high-AI-exposure and low-AI-exposure majors.

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    {'url': 'https://nces.ed.gov/programs/digest/d22/tables/xls/tabn505.10.xlsx', 'filename': 'nces_505_10_d22.xlsx'},
    {'url': 'https://nces.ed.gov/programs/digest/d21/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d21.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d20/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d20.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d19/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d19.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d18/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d18.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d17/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d17.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d16/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d16.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d15/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d15.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d14/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d14.xls'},
    {'url': 'https://nces.ed.gov/programs/digest/d13/tables/xls/tabn505.10.xls', 'filename': 'nces_505_10_d13.xls'},
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/10 [00:00<?, ?it/s]
Downloading nces_505_10_d22.xlsx:   0%|          | 0.00/51.7k [00:00<?, ?B/s]
Downloading nces_505_10_d22.xlsx:  36%|███▌      | 18.4k/51.7k [00:00<00:00, 135kB/s]
Downloading nces_505_10_d22.xlsx:  67%|██████▋   | 34.8k/51.7k [00:00<00:00, 124kB/s]
Overall Download Progress:  10%|█         | 1/10 [00:00<00:06,  1.31it/s]

Successfully downloaded: nces_505_10_d22.xlsx

Downloading nces_505_10_d21.xls:   0%|          | 0.00/30.6k [00:00<?, ?B/s]
Downloading nces_505_10_d21.xls: 41.0kB [00:00, 301kB/s]
Overall Download Progress:  20%|██        | 2/10 [00:01<00:05,  1.42it/s]

Successfully downloaded: nces_505_10_d21.xls

Downloading nces_505_10_d20.xls:   0%|          | 0.00/30.6k [00:00<?, ?B/s]
Downloading nces_505_10_d20.xls: 41.0kB [00:00, 307kB/s]
Overall Download Progress:  30%|███       | 3/10 [00:02<00:04,  1.49it/s]

Successfully downloaded: nces_505_10_d20.xls

Downloading nces_505_10_d19.xls:   0%|          | 0.00/28.9k [00:00<?, ?B/s]
Downloading nces_505_10_d19.xls: 37.9kB [00:00, 280kB/s]
Overall Download Progress:  40%|████      | 4/10 [00:02<00:03,  1.51it/s]

Successfully downloaded: nces_505_10_d19.xls

Downloading nces_505_10_d18.xls:   0%|          | 0.00/32.7k [00:00<?, ?B/s]
Downloading nces_505_10_d18.xls: 42.0kB [00:00, 317kB/s]
Overall Download Progress:  50%|█████     | 5/10 [00:03<00:03,  1.54it/s]

Successfully downloaded: nces_505_10_d18.xls

Downloading nces_505_10_d17.xls:   0%|          | 0.00/32.7k [00:00<?, ?B/s]
Downloading nces_505_10_d17.xls: 42.0kB [00:00, 301kB/s]
Overall Download Progress:  60%|██████    | 6/10 [00:04<00:02,  1.51it/s]

Successfully downloaded: nces_505_10_d17.xls

Downloading nces_505_10_d16.xls:   0%|          | 0.00/32.6k [00:00<?, ?B/s]
Downloading nces_505_10_d16.xls: 42.0kB [00:00, 351kB/s]
Overall Download Progress:  70%|███████   | 7/10 [00:04<00:01,  1.53it/s]

Successfully downloaded: nces_505_10_d16.xls

Downloading nces_505_10_d15.xls:   0%|          | 0.00/29.5k [00:00<?, ?B/s]
Downloading nces_505_10_d15.xls: 42.0kB [00:00, 312kB/s]
Overall Download Progress:  80%|████████  | 8/10 [00:05<00:01,  1.53it/s]

Successfully downloaded: nces_505_10_d15.xls

Downloading nces_505_10_d14.xls:   0%|          | 0.00/26.6k [00:00<?, ?B/s]
Downloading nces_505_10_d14.xls: 46.1kB [00:00, 350kB/s]
Overall Download Progress:  90%|█████████ | 9/10 [00:05<00:00,  1.53it/s]

Successfully downloaded: nces_505_10_d14.xls

Downloading nces_505_10_d13.xls:   0%|          | 0.00/23.6k [00:00<?, ?B/s]
Downloading nces_505_10_d13.xls: 49.2kB [00:00, 365kB/s]
Overall Download Progress: 100%|██████████| 10/10 [00:06<00:00,  1.52it/s]

Successfully downloaded: nces_505_10_d13.xls

### NCES Field-of-Study Employment Outcomes Dataset


This dataset comes from NCES Digest of Education Statistics Table 505.10, which reports employment outcomes for 25- to 29-year-old bachelor’s degree holders by field of study. The original tables include metrics such as number of degree holders, percentage distribution, unemployment rate, median annual earnings, and the percentage of all 25- to 29-year-olds with a degree in each field. The NCES tables report standard errors in parentheses, which means many values are estimates based on survey data rather than exact population values. The data are based on American Community Survey 1-Year PUMS data. 

The main metric for this project is unemployment rate, measured as a percentage of the civilian labor force within each field of study. For example, an unemployment rate of 4.5 means that 4.5% of people in that field’s civilian labor force were unemployed. The unit is percentage points, so a change from 3.0 to 5.0 is a 2 percentage point increase. Other variables in the raw tables, such as number of degree holders and median annual earnings, are useful for context but are not the main dependent variable in our difference-in-differences model. NCES reports median earnings for full-time, year-round workers, while the number of degree holders is reported in thousands. 

For this project, we will extract unemployment rates for eight selected fields from 2012 to 2021. The high-AI-exposure group includes Computer Science, Engineering, Mathematics, and Physics. The low-AI-exposure group includes History, Art, Philosophy, and Political Science. After cleaning, the dataset will be tidy because each row will represent one major in one year, with separate columns for major, year, unemployment_rate, ai_exposure_group, post_2017, and did_interaction (It equals 1 only when both conditions are true: 1) The major is in the high-AI-exposure group. 2) The year is after 2017).

There are several concerns with this dataset. First, the raw NCES tables are not already in a tidy panel format, so the relevant rows and years must be extracted manually. Second, some field names do not perfectly match our simplified major names. For example, Computer Science appears as “Computer and information sciences,” Art appears as “Arts, fine and commercial,” and Physics may need to be represented by the broader “Physical sciences” category. Third, the data are observational, so the project cannot prove that AI exposure caused changes in unemployment rates. Finally, the analysis may be affected by other labor-market shocks, especially COVID-19, and by the small number of selected majors.

In [3]:
# import packages
import pandas as pd

In [4]:
# Specify Year
file_years = {
    'nces_505_10_d13.xls': 2012, 
    'nces_505_10_d14.xls': 2013, 
    'nces_505_10_d15.xls': 2014, 
    'nces_505_10_d16.xls': 2015,
    'nces_505_10_d17.xls': 2016,
    'nces_505_10_d18.xls': 2017,
    'nces_505_10_d19.xls': 2018,
    'nces_505_10_d20.xls': 2019,
    'nces_505_10_d21.xls': 2020,
    'nces_505_10_d22.xlsx': 2021,
}

# Define a major map
major_map = {
    'Computer and information sciences': 'Computer Science', 
    'Computer and information systems': 'Computer Science',
    'General engineering': 'Engineering',
    'Mathematics': 'Mathematics',
    'Physical sciences': 'Physics',
    'History': 'History',
    'Fine arts': 'Art',
    'Philosophy and religious studies': 'Philosophy',
    'Political science and government': 'Political Science',
}

# High AI Exposure
High_AI = ['Computer Science', 'Physics', 'Engineering', 'Mathematics']

In [5]:
# take a look
check = pd.read_excel('data/00-raw/nces_505_10_d17.xls', header=None)
check

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,NaN,"Table 505.10. Number, percentage distribution,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,[Standard errors appear in parentheses],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Field of study and STEM status of field,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,25- to 29-year-old bachelor's degree holders,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Percent of all 25- to 29-year-olds with degree...,NaN,NaN
4,NaN,NaN,"Number, in thousands",NaN,NaN,Percentage distribution,NaN,NaN,Unemployment rate for the civilian labor force,NaN,...,NaN,Unemployment rate for the civilian labor force,NaN,NaN,Median annual earnings of full-time year-round...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,NaN,‡Reporting standards not met. Either there are...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,\1\Constant dollars based on the Consumer Pric...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,\2\STEM fields include biological and biomedic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NOTE: The first bachelor’s degree major report...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,NaN,"SOURCE: U.S. Department of Commerce, Census Bu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Function for cleaning the files
def clean_file(file, year):
    path = 'data/00-raw/' + file
    df = pd.read_excel(path, header = None)
    df = pd.DataFrame({
        'major_raw': df.iloc[:, 1],
        'unemployment_rate': df.iloc[:, -9]
    })
    df = df[['major_raw', 'unemployment_rate']].copy()
    
    df['major_raw'] = df['major_raw'].str.replace(r'\.+', '', regex=True).str.replace(r'\s+', ' ', regex=True).astype(str).str.strip()

    df['unemployment_rate'] = pd.to_numeric(
        df['unemployment_rate'],
        errors='coerce'
    )
    
    df = df[df['major_raw'].isin(major_map.keys())].copy()

    df['major'] = df['major_raw'].map(major_map)
    df['year'] = year

    df = df[['major', 'year', 'unemployment_rate']]

    # drop any null values
    df = df.dropna()

    return df

In [7]:
parts = []

# loop through each year
for file, year in file_years.items():
    template = clean_file(file, year)
    
    #store intermediate data
    template.to_csv(
        'data/01-interim/nces_' + str(year) + '_cleaned.csv',
        index=False
    )
    
    # add to the list
    parts.append(template)
    
# combine into pivot_long format
cleaned_df = pd.concat(parts, ignore_index=True)

In [8]:
# add variable
cleaned_df['ai_exposure_group'] = cleaned_df['major'].isin(High_AI).astype(int)

cleaned_df['post_2017'] = (cleaned_df['year']>=2018).astype(int)

cleaned_df['did_interaction'] = cleaned_df['ai_exposure_group'] * cleaned_df['post_2017']

In [9]:
# check shape
cleaned_df.shape
cleaned_df

,major,year,unemployment_rate,ai_exposure_group,post_2017,did_interaction
0,Art,2012,6.625376,0,0,0
1,Computer Science,2012,4.506926,1,0,0
2,Engineering,2012,4.447880,1,0,0
3,History,2012,5.810965,0,0,0
4,Mathematics,2012,2.677093,1,0,0
...,...,...,...,...,...,...
75,History,2021,4.039182,0,1,0
76,Mathematics,2021,4.667823,1,1,1
77,Physics,2021,4.427999,1,1,1
78,Philosophy,2021,5.923490,0,1,0
79,Political Science,2021,6.046438,0,1,0

In [10]:
# store cleaned data
cleaned_df.to_csv('data/02-processed/nces_did_final.csv', index=False)

## Ethics


Instructions: Keep the contents of this cell. For each item on the checklist
-  put an X there if you've considered the item
-  IF THE ITEM IS RELEVANT place a short paragraph after the checklist item discussing the issue.
  
Items on this checklist are meant to provoke discussion among good-faith actors who take their ethical responsibilities seriously. Your teams will document these discussions and decisions for posterity using this section.  You don't have to solve these problems, you just have to acknowledge any potential harm no matter how unlikely.

Here is a [list of real world examples](https://deon.drivendata.org/examples/) for each item in the checklist that can refer to.

[![Deon badge](https://img.shields.io/badge/ethics%20checklist-deon-brightgreen.svg?style=popout-square)](http://deon.drivendata.org/)

### A. Data Collection
 - [X] **A.1 Informed consent**: This project uses public NCES data and does not directly collect information from human participants. Therefore, informed consent is not directly required for our project. However, if we later collect interview or survey data from students, participants would need to be clearly informed about what data is collected, how it will be used, and whether they consent to participate.

 - [X] **A.2 Collection bias**: Since we use existing NCES data, we need to consider how the original data was collected. The data may be affected by sampling methods, survey response rates, non-response bias, or changes in data collection standards across years. These issues could affect how accurately the dataset represents all bachelor’s degree holders.

 - [X] **A.3 Limit PII exposure**: Our dataset is publicly available and does not include personal identifiers. Therefore, the risk of exposing personal information is low. If any personal information appears in the data unexpectedly, we should remove it before analysis.

 - [X] **A.4 Downstream bias mitigation**: Although this project does not compare individuals or protected demographic groups, it may still create bias around major choices. Readers might interpret some majors as more or less valuable based only on unemployment trends. To reduce this risk, we should explain that employment outcomes are affected by many factors, including graduate school enrollment, industry demand, economic conditions, and COVID-19, not AI exposure alone.

### B. Data Storage
 - [X] **B.1 Data security**: The dataset is public and does not contain sensitive personal information, so the security risk is limited. However, we should still store our cleaned data, notebooks, and code in the project repository carefully and avoid adding any unnecessary private information.

 - [X] **B.2 Right to be forgotten**: Since we do not directly collect individual-level participant data, the right to be forgotten is mostly not relevant to this project. If we later use any non-public individual-level data, we would need a process for removing a participant’s data if they request withdrawal.

 - [X] **B.3 Data retention plan**: We will keep the original data source links, cleaned datasets, and analysis code for reproducibility. Since the data is public, long-term retention is acceptable, but we should clearly document which files are raw data, cleaned data, and final outputs.

### C. Analysis
 - [X] **C.1 Missing perspectives**: Our analysis may miss perspectives from students, career advisors, employers, or universities. We plan to consider perspectives from the UCSD Career Center or similar career-related sources to better understand how major choice, graduate school enrollment, and labor-market demand affect employment outcomes.

 - [X] **C.2 Dataset bias**: The dataset may contain bias because field-of-study categories are broad and do not perfectly match our simplified major groups. There may also be confounding variables, such as COVID-19, economic cycles, immigration policies, industry demand, and changes in graduate school enrollment. These factors may affect unemployment trends independently from AI exposure.

 - [X] **C.3 Honest representation**: We should present the data honestly and avoid exaggerating the findings. Visualizations should clearly label years, major groups, and unemployment rates. We should not present small differences as major effects or imply causation if the evidence only supports an association.

 - [X] **C.4 Privacy in analysis**: The analysis uses aggregate public data by field of study, so privacy risk is low. However, we should avoid trying to infer individual-level outcomes from group-level statistics.

 - [X] **C.5 Auditability**: Our analysis should be reproducible. We will keep the raw data links, cleaning steps, code, and model specification in the notebook. Since we plan to use a difference-in-differences regression model, we should clearly document how we define high-AI-exposure majors, low-AI-exposure majors, pre/post-2017, and the interaction term.

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Our model uses major groups as the main comparison, but major choice may indirectly reflect factors such as gender, socioeconomic background, access to education, or family resources. Therefore, we should avoid interpreting the results as showing that students from certain majors are inherently more or less employable. The model should only be used to discuss broad employment trends across fields of study.

 - [X] **D.2 Fairness across groups**: We compare high-AI-exposure majors and low-AI-exposure majors using the same data source, same time period, and same outcome variable. However, the grouping is still simplified because each major contains many different students and career paths. Therefore, we need to be careful not to overgeneralize the results to every student within each major.

 - [X] **D.3 Metric selection**: The main metric in our model is unemployment rate, which directly connects to our research question. 

 - [X] **D.4 Explainability**: We plan to use a difference-in-differences regression model. This model is relatively explainable because the key coefficient shows whether unemployment rates changed differently after 2017 for high-AI-exposure majors compared with low-AI-exposure majors. This makes the result easier to communicate than a more complex machine learning model.

 - [X] **D.5 Communicate limitations**: The result should not be presented as definite causal proof that AI caused changes in unemployment rates. Other factors, such as COVID-19, economic changes, industry demand, and graduate school enrollment, may also affect employment outcomes. Therefore, our conclusion should be framed as evidence of an association or trend, not as a complete explanation of AI’s effect on college graduates.

### E. Deployment
 - [X] **E.1 Monitoring and evaluation**: This project does not deploy a predictive model, but the results could still be misinterpreted. For example, universities or students might treat the findings as a ranking of majors or as evidence that some fields are no longer valuable. To reduce this risk, the final report should clearly state that the findings describe historical patterns and should not be used to make predictions or judgments about individual students.

 - [X] **E.2 Redress**: Since this project does not directly affect individuals through a deployed system, there is no formal redress process. However, if readers identify mistakes in our data cleaning, grouping of majors, or interpretation, we should be open to correcting the analysis and updating the report.

 - [X] **E.3 Roll back**: If we find major errors in our dataset, model specification, or interpretation, we should revise or remove the affected results. Since the project is a research report rather than a deployed tool, “rolling back” mainly means updating the notebook, correcting the written explanation, and clearly noting the change.

 - [X] **E.4 Unintended use**: The results may be unintentionally used to discourage students from choosing certain majors or to overstate the impact of AI on employment outcomes. To prevent this, we should emphasize that the analysis is limited to selected majors, selected years, and unemployment rates only. It should not be used as career advice or as a full measure of a major’s value.

## Team Expectations

Team Expectation 1: We will communicate regularly through our agreed group chat and respond to project-related messages within 24 hours when possible.

Team Expectation 2: We will meet at least once a week to check progress, divide tasks, and discuss any problems with the project.

Team Expectation 3: Tasks will be divided fairly based on each member’s strengths, but everyone should contribute to research, coding, writing, and editing.

Team Expectation 4: We will use a shared document or project tracker to record tasks, deadlines, and progress so everyone knows what needs to be done.

Team Expectation 5: We will communicate respectfully and give feedback in a polite but direct way. If we disagree, we will explain our reasoning and try to find a solution together.

Team Expectation 6: If someone is struggling to complete a task, they should tell the group as early as possible so the team can adjust the workload or deadline.

Team Expectation 7: If a team member repeatedly does not communicate or complete agreed tasks, the group will first contact them directly in writing. If the issue continues, we will contact the professor.

## Project Timeline Proposal

| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|---|---|---|---|
| 5/13 | 10 AM | Read COGS 108 expectations; confirm research question about AI exposure and unemployment by college major | Finalize communication method, team expectations, project topic, hypothesis, and ethics checklist |
| 5/16 | 12 PM | Conduct background research on AI exposure, labor-market changes, and NCES unemployment data | Finalize datasets; discuss data limitations; assign roles for data cleaning, EDA, analysis, and writing |
| 5/20 | 12 PM | Import NCES tables; check field-of-study names across years; begin cleaning data | Review wrangling progress; decide final major mapping for high-AI-exposure and low-AI-exposure groups |
| 5/25 | 6 PM | Complete data cleaning; create initial EDA graphs of unemployment trends by major/group | Review EDA results; discuss possible confounding variables and whether the data supports our hypothesis |
| 5/30 | 12 PM | Begin difference-in-differences regression model; document model variables and assumptions | Review model results; discuss interpretation, limitations, and possible robustness checks |
| 6/5 | 12 PM | Finalize analysis; draft results, discussion, ethics, and conclusion sections | Edit full notebook; check code readability, figures, citations, and whether claims are supported by data |
| 6/10 | 6 PM | Complete final proofreading; make sure all team members’ contributions are included | Final review before submission; fix formatting, grammar, and any remaining issues |
| Final Due Date | Before 11:59 PM | NA | Submit final project and group project surveys |